JWT_SECRET: ${JWT_SECRET}
spring:
    datasource:
        password: ${password}
        platform: postgres
        url: ${DATABASE_URL}
        username: ${username}
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: ${clientId}
                        clientSecret: ${clientSecret}
                        redirectUri: ${redirectUri}
                        scope: 
                          - email
                          - profile