spring:
    profiles:
      active: dev
    application.name: warehouse-service
#    config.import: optional:configserver:http://localhost:8088
    config.import: optional:configserver:${CONFIGSERVER_URL} #for production
    mail:
       host: smtp.gmail.com
       port: 587
       username: phuoccong99@gmail.com
       password: hsovbgfxyapejfmx
       properties:
             mail:
               smtp:
                 auth: true
                 starttls:
                    enable: true
mail:
     smtp:
         debug: true
