spring:
    profiles:
      active: prod
    application.name: warehouse-service
#    config.import: optional:configserver:http://localhost:8088
    config.import: optional:configserver:${CONFIGSERVER_URL} #for production
    mail:
       host: ${host}
       port: ${port}
       username: ${usernameMail}
       password: ${passwordMail}
       properties:
             mail:
               smtp:
                 auth: true
                 starttls:
                    enable: true
mail:
     smtp:
         debug: true
